[Main]
name = Reactor (5x5cm, Spyral, 0.35 mm nozzle)
description = PDMS-based LSC-PM 5x5cm w/ spyral design

[LSC]
thickness = 0.003
width = 0.05
length = 0.05

[Channels]
channels = [([0.004775000000000001, 0.0, 0.001], [0.0010500000000000002, 0.01, 0.001], 'box', 'Channel0'), ([0.005125, 0.01, 0.001], [0.00035, 0.03615, 0.001], 'box', 'Channel1'), ([0.005475, 0.0458, 0.001], [0.03125, 0.00035, 0.001], 'box', 'Channel2'), ([0.036725, 0.01165, 0.001], [0.00035, 0.0345, 0.001], 'box', 'Channel3'), ([0.021075, 0.01165, 0.001], [0.01565, 0.00035, 0.001], 'box', 'Channel4'), ([0.020725, 0.01165, 0.001], [0.00035, 0.0189, 0.001], 'box', 'Channel5'), ([0.021075, 0.0302, 0.001], [0.00375, 0.00035, 0.001], 'box', 'Channel6'), ([0.024825, 0.01945, 0.001], [0.00035, 0.0111, 0.001], 'box', 'Channel7'), ([0.025175000000000003, 0.01945, 0.001], [0.00375, 0.00035, 0.001], 'box', 'Channel8'), ([0.028925000000000003, 0.01945, 0.001], [0.00035, 0.0189, 0.001], 'box', 'Channel9'), ([0.013275, 0.038, 0.001], [0.01565, 0.00035, 0.001], 'box', 'Channel10'), ([0.012925, 0.00385, 0.001], [0.00035, 0.0345, 0.001], 'box', 'Channel11'), ([0.013275, 0.00385, 0.001], [0.03125, 0.00035, 0.001], 'box', 'Channel12'), ([0.044525, 0.00385, 0.001], [0.00035, 0.03615, 0.001], 'box', 'Channel13'), ([0.044175, 0.04, 0.001], [0.0010500000000000002, 0.01, 0.001], 'box', 'Channel14')]

; #        ORIGIN:  X        Y     Z  L:   X      Y   Z
; geometry.append(((4.775, 0.000, 1), (1.05, 10.00, 1)))  # Inlet, bigger for the first 10 mm
; geometry.append(((5.125, 10.000, 1), (0.35, 36.15, 1)))  # 1st channel left
; geometry.append(((5.475, 45.800, 1), (31.25, 0.35, 1)))  # 1st channel bottom
; geometry.append(((36.725, 11.650, 1), (0.35, 34.50, 1)))  # 2nd channel right
; geometry.append(((21.075, 11.650, 1), (15.65, 0.35, 1)))  # 2nd channel top
; geometry.append(((20.725, 11.650, 1), (0.35, 18.90, 1)))  # 3rd channel left
; geometry.append(((21.075, 30.200, 1), (3.75, 0.35, 1)))  # 3nd channel bottom
; geometry.append(((24.825, 19.450, 1), (0.35, 11.10, 1)))  # Middle piece
; geometry.append(((25.175, 19.450, 1), (3.75, 0.35, 1)))  # 3nd channel top
; geometry.append(((28.925, 19.450, 1), (0.35, 18.90, 1)))  # 3nd channel right
; geometry.append(((13.275, 38.000, 1), (15.65, 0.35, 1)))  # 2nd channel bottom
; geometry.append(((12.925, 3.850, 1), (0.35, 34.50, 1)))  # 2nd channel left
; geometry.append(((13.275, 3.850, 1), (31.25, 0.35, 1)))  # 1st channel top
; geometry.append(((44.525, 3.850, 1), (0.35, 36.15, 1)))  # 1st channel right
; geometry.append(((44.175, 40.000, 1), (1.05, 10.00, 1)))  # Outlet, bigger for the first 10 mm
